# Generated by Django 4.0.4 on 2022-05-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product gallety', 'verbose_name_plural': 'Product gallery'},
        ),
    ]
