# Generated by Django 4.0.4 on 2022-04-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='ammount_paid',
            new_name='amount_paid',
        ),
    ]
