# Generated by Django 4.0.4 on 2022-04-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_ammount_paid_payments_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='paymennt_id',
            new_name='payment_id',
        ),
    ]
